/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bostonemployeemanagementsystem;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Millez Millenium
 */
public class SalaryPortal extends javax.swing.JFrame {

    Boolean boolRecordExists=false;
    Boolean boolEdit=false;
    Boolean boolCreate=false;
    String strFirstName=null;
    String strSurname=null;
    String strDepartment=null;
    String strDateOfBirth=null;
    String strBasicSalary=null;
    String strEmployeeID=null;
    String strTotalOverTime=null;
    String strPassword=null;
    int intEmployeeID;
    
    private void mGetValuesFromGUI()
        {
         strFirstName = txtFirstName.getText();
         strSurname = txtSurname.getText();
         strDepartment = txtDepartment.getText();
         strDateOfBirth = txtDateOfBirth.getText();
         strBasicSalary = txtBasicSalary.getText();
         strEmployeeID = txtEmployeeID.getText();
         
        }
    
    private void mSetValuesToUpperCase()
    {
        strFirstName = txtFirstName.getText();
         strEmployeeID = txtEmployeeID.getText();
         strDepartment = txtDepartment.getText();
         strDateOfBirth = txtDateOfBirth.getText();
         strBasicSalary = txtBasicSalary.getText();
    }
    
    private void mCheckIfItemsExistInTable()
    {
        String strDBConnectionString="jdbc:mysql://localhost:3306/employee_management_system";
        String strDBUser="root";
        String strDBPassword="password";
        java.sql.Connection conMySQLConnectionString;
        Statement stStatement=null;
        ResultSet rs=null;
        try
        {
         conMySQLConnectionString = DriverManager.getConnection(strDBConnectionString, strDBUser, strDBPassword);
         stStatement = conMySQLConnectionString.createStatement();
         String strQuery = " Select * from employee_information where employee_id='" + strEmployeeID + "' and basic_salary'" + strBasicSalary +  "'";
         stStatement.execute(strQuery);
         rs=stStatement.getResultSet();
         boolRecordExists=rs.next();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try{
                stStatement.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Connection String not closed" + " " + e);
            }
        }
    }
    
    private void mCreateActor()
    {
        java.sql.Connection conMySQLConnectionString = null;
        String URL= "jdbc:mysql://localhost:3306/employee_management_system";
        String User="root";
        String Password="password";
        try
        {
            conMySQLConnectionString = DriverManager.getConnection(URL,User,Password);
            Statement myStatement = conMySQLConnectionString.createStatement();
            String sqlinsert = " insert into employee_information"+" (employee_id,basic_salary)"+"values('" + strEmployeeID + "', '" + strBasicSalary + "',')";
            myStatement.executeUpdate(sqlinsert);
            myStatement.close();
            lblOutput.setText("Employee Successfully Added");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
     private void mClearTextFields()
        {
            txtFirstName.setText("");
            txtSurname.setText("");
            txtDateOfBirth.setText("");
            txtDepartment.setText("");
            txtBasicSalary.setText("");
        }
    
    /**
     * Creates new form SalaryPortal
     */
    public SalaryPortal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblAdministrator = new javax.swing.JLabel();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblSurname = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        lblDateOfBirth = new javax.swing.JLabel();
        txtDateOfBirth = new javax.swing.JTextField();
        lblBasicSalary = new javax.swing.JLabel();
        txtBasicSalary = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        lblOvertime = new javax.swing.JLabel();
        lblMedical = new javax.swing.JLabel();
        lblBonus = new javax.swing.JLabel();
        lblOther = new javax.swing.JLabel();
        txtOvertime = new javax.swing.JTextField();
        txtMedical = new javax.swing.JTextField();
        txtBonus = new javax.swing.JTextField();
        txtOther = new javax.swing.JTextField();
        lblTotalOverTime = new javax.swing.JLabel();
        lblRatePerHour = new javax.swing.JLabel();
        txtTotalOvertime = new javax.swing.JTextField();
        txtRatePerHour = new javax.swing.JTextField();
        lblAmounts = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        lblTotalAmount = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblAdministrator.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblAdministrator.setForeground(new java.awt.Color(102, 102, 102));
        lblAdministrator.setText("Employee Management System: Salary Portal");

        lblEmployeeID.setText("Employee ID:");

        lblFirstName.setText("First Name:");

        lblSurname.setText("Surname:");

        lblDateOfBirth.setText("Date of Birth:");

        lblBasicSalary.setText("Basic Salary:");

        lblDepartment.setText("Department:");

        lblOvertime.setText("Overtime:");

        lblMedical.setText("Medical:");

        lblBonus.setText("Bonus:");

        lblOther.setText("Other:");

        txtOvertime.setText("0");

        txtMedical.setText("0");

        txtBonus.setText("0");

        txtOther.setText("0");

        lblTotalOverTime.setText("Total Overtime:");

        lblRatePerHour.setText("Rate Per Hour:");

        txtTotalOvertime.setText("0");

        txtRatePerHour.setText("0");

        lblAmounts.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAmounts.setText("Please Enter The Amount");

        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spTable.setViewportView(tblTable);

        lblTotalAmount.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotalAmount.setText("Total Amount:");

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCalculate.setBackground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblOutput.setBackground(new java.awt.Color(255, 255, 255));
        lblOutput.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOutput.setText("0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSave)
                                    .addComponent(btnClear)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTotalAmount)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblOutput))
                                    .addComponent(btnCalculate)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEmployeeID)
                                            .addComponent(lblFirstName))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(txtEmployeeID)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDateOfBirth)
                                            .addComponent(lblSurname)
                                            .addComponent(lblBasicSalary)
                                            .addComponent(lblDepartment))
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBasicSalary, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtDateOfBirth, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtSurname)
                                            .addComponent(txtDepartment))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblOvertime)
                                            .addComponent(lblMedical)
                                            .addComponent(lblBonus)
                                            .addComponent(lblOther))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtOther, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(txtBonus)
                                            .addComponent(txtMedical)
                                            .addComponent(txtOvertime))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRatePerHour)
                                            .addComponent(lblTotalOverTime))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTotalOvertime, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(txtRatePerHour)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(171, 171, 171)
                                        .addComponent(lblAmounts)))))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblAdministrator)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdministrator)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeID)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmounts))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOvertime)
                    .addComponent(txtOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalOverTime)
                    .addComponent(txtTotalOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedical)
                    .addComponent(txtMedical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRatePerHour)
                    .addComponent(txtRatePerHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfBirth)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBonus)
                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBasicSalary)
                    .addComponent(txtBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOther)
                    .addComponent(txtOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalAmount)
                            .addComponent(lblOutput))
                        .addGap(51, 51, 51)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    WelcomePage WelcomePage = new WelcomePage();
    WelcomePage.show();
    this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        int BasicSalary = Integer.parseInt(txtBasicSalary.getText());
        int Overtime = Integer.parseInt(txtOvertime.getText());

        double eight = 8;
        double days = 25;
        double dbop = 0;
        double RatePerHour = 1.5;
        
        //calculate the total hours of overtime
        double TotalOvertime = Overtime * RatePerHour;
        String x = String.valueOf(TotalOvertime);
        txtTotalOvertime.setText(x);

        //calculate overall overtime 
        dbop = BasicSalary /days/eight;
        String s = String.valueOf(dbop);
        txtRatePerHour.setText(s);
        
        int med = Integer.parseInt(txtMedical.getText());
        int bonus = Integer.parseInt(txtBonus.getText());
        int other = Integer.parseInt(txtOther.getText());
        int f = med+bonus+other;
        double calc = TotalOvertime * dbop+f;
        String c = String.valueOf(calc);
        lblOutput.setText(c);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    
     int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to Save?","Save Salary Information",JOptionPane.YES_NO_OPTION);
        if(p==0){
            String firstname = txtFirstName.getText();
String surname = txtSurname.getText();
String department = txtDepartment.getText();
String dateofbirth = txtDateOfBirth.getText();
String employeeid = txtEmployeeID.getText();
String basicsalary = txtBasicSalary.getText();
String bonus = txtBonus.getText();
String totalovertime = txtTotalOvertime.getText();


if (txtFirstName.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Enter your First Name");
   
}
else if(txtSurname.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Enter your Surname");
    
}
else if(txtDepartment.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Enter your Department");
    
}
else if(txtDateOfBirth.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Enter your Date of Birth");
    
}
else if(txtEmployeeID.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Enter your ID Number");
    
}
else if(txtBasicSalary.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Enter your Salary");
    
}
else if(txtBonus.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Enter Bonus Amount");
    
}
else{
    JOptionPane.showMessageDialog(null, "Saved Succssfully");
    DefaultTableModel model = (DefaultTableModel) tblTable.getModel();
         model.addRow(new Object[] {txtBasicSalary.getText(),txtTotalOvertime.getText(),txtBonus.getText(),lblOutput.getText()});
    mGetValuesFromGUI();
        mSetValuesToUpperCase();
        mCheckIfItemsExistInTable();
        if(boolRecordExists==true)
           {
             boolRecordExists=false;
             lblOutput.setText("Employee already exists");
           }
        else if(boolRecordExists=false)
           {
              mCreateActor();
              mClearTextFields();
           }
    }
        try{
        }catch(Exception e){
        }finally {
            try{    
            }
            catch(Exception e){
            }
        }
        
        }  
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtFirstName.setText("");
        txtSurname.setText("");
        txtDateOfBirth.setText("");
        txtDepartment.setText("");
        txtBasicSalary.setText("");
        txtOvertime.setText("0");
        txtBonus.setText("0");
        txtOther.setText("0");
        txtMedical.setText("0");
        txtRatePerHour.setText("0");
        txtEmployeeID.setText("");
        txtTotalOvertime.setText("0");
        lblOutput.setText("0.00");// TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdministrator;
    private javax.swing.JLabel lblAmounts;
    private javax.swing.JLabel lblBasicSalary;
    private javax.swing.JLabel lblBonus;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblMedical;
    private javax.swing.JLabel lblOther;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblOvertime;
    private javax.swing.JLabel lblRatePerHour;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblTotalOverTime;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JTable tblTable;
    private javax.swing.JTextField txtBasicSalary;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtMedical;
    private javax.swing.JTextField txtOther;
    private javax.swing.JTextField txtOvertime;
    private javax.swing.JTextField txtRatePerHour;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtTotalOvertime;
    // End of variables declaration//GEN-END:variables
}
